FROM postgres:17.5

# Setze Umgebungsvariablen für Initialisierung
ENV POSTGRES_DB=testdb
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=pass

# Optional: UTF-8 Encoding sicherstellen
ENV LANG="en_US.utf8"
